/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Controladora.ControlPresentacion;
import DTO.ValidacionesLocacion;
import com.mycompany.mapainteractivopersistencia.LocacionDTO;
import com.mycompany.mapainteractivopersistencia.UsuarioDTO;

/**
 *
 * @author favel
 */
public class DlgRegistroLocacion extends javax.swing.JFrame {

    UsuarioDTO sesionUsuario;
    ControlPresentacion control = new ControlPresentacion(sesionUsuario);
    ValidacionesLocacion vLocacion = new ValidacionesLocacion();
    LocacionDTO sesionLocacion = new LocacionDTO();
    
    /**
     * Creates new form DlgRegistroLocacion
     */
    public DlgRegistroLocacion(UsuarioDTO usuario) {
        initComponents();
        this.setVisible(true);
        this.sesionUsuario = usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonRegreso = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombreLocacion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcionLocacion = new javax.swing.JTextArea();
        btnRegistrarLocacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonRegreso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButtonRegreso.setForeground(new java.awt.Color(255, 255, 255));
        ButtonRegreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-back.png"))); // NOI18N
        ButtonRegreso.setBorder(null);
        ButtonRegreso.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonRegreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRegresoActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonRegreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 60, 40));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo_ITSON (1)_2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 110));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Descripcion de locacion:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 310, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nombre de locacion:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 310, 30));

        nombreLocacion.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jPanel2.add(nombreLocacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 300, -1));

        descripcionLocacion.setColumns(20);
        descripcionLocacion.setRows(5);
        jScrollPane1.setViewportView(descripcionLocacion);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 300, 170));

        btnRegistrarLocacion.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnRegistrarLocacion.setText("Registrar Locacion");
        btnRegistrarLocacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarLocacionActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegistrarLocacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 230, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 880, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonRegresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRegresoActionPerformed
        control.deplegarMenu();
        dispose();
    }//GEN-LAST:event_ButtonRegresoActionPerformed

    private void btnRegistrarLocacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarLocacionActionPerformed
        String nombre = nombreLocacion.getText();
        String descripcion = descripcionLocacion.getText();
        sesionLocacion = vLocacion.registrarLocacion(nombre, descripcion);
        if (sesionLocacion == null) {
            System.out.println("Se registro la locacion: DlgRegistroLocacion");
        } else {
            System.out.println("No se registro: DlgRegistro");
        }
    }//GEN-LAST:event_btnRegistrarLocacionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonRegreso;
    private javax.swing.JButton btnRegistrarLocacion;
    private javax.swing.JTextArea descripcionLocacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombreLocacion;
    // End of variables declaration//GEN-END:variables
}
