package Vistas;

import Controladora.ControlPresentacion;
import DAOS.LocacionDAO;
import Validaciones.ValidacionesLocacion;
import POJOs.LocacionPOJO;
import POJOs.UsuarioPOJO;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.util.List;

/**
 *
 * @author JOSUE GOMEZ
 */
public class frmMapa extends javax.swing.JFrame {
  // Gestiona la sesión iniciada
    private UsuarioPOJO sesion;
    // Funciona para mantener la última locación seleccionada
    private JLabel ultimoLabelActivado = null;
    // Funciona para mantener los puntos de interés visibles
    private boolean puntosVisibles = true;
    private ValidacionesLocacion vLocacion = new ValidacionesLocacion();
    private List<JLabel> puntos;
ControlPresentacion control;
   LocacionPOJO sesionLocacion = new LocacionPOJO();
    /**
     * Creates new form MapaInteractivo
     *
     * @param parent
     * @param modal
     */
    public frmMapa(java.awt.Frame parent, boolean modal) {
        initComponents();
    }

    public frmMapa(UsuarioPOJO usuario) {
        initComponents();
        this.sesion = usuario;
        control = new ControlPresentacion(sesion);
        puntos = vLocacion.devolverListaLabels();
        this.mostrarPuntos(puntos);
        this.asignarEventos(puntos);
        System.out.println("...................LISTA MAPA.........................");
        for (int i = 0; i <puntos.size(); i++) {
                  System.out.println(puntos.get(i).toString());
             }
        System.out.println("..........................................................");
        this.bienvenidaSesion();
        System.out.println("---------------------------------------------------------------------------"
                + "\nDlgMenuLocaciones - Imprimiento tu sesion: " + sesion
                + "\n---------------------------------------------------------------------------");
        this.setVisible(true);
        txtBusqueda.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (txtBusqueda.getText().equals("Búsqueda...")) {
                    txtBusqueda.setText("");
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
            }
        });
        txtBusqueda.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String busqueda = txtBusqueda.getText();
                List<String> resultados = vLocacion.buscarLocaciones(busqueda);
                // Aquí puedes actualizar tu interfaz gráfica con los resultados de la búsqueda
                // Por ejemplo, podrías mostrar los resultados en un JList o JComboBox
                if (!resultados.isEmpty()) {
                    // Mostrar la información de la primera locación que coincide con la búsqueda
                    LocacionPOJO locacion = vLocacion.verificarLocacion(resultados.get(0));
                    mostrarInformacion(locacion);

                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AV1400 = new javax.swing.JLabel();
        AV1000 = new javax.swing.JLabel();
        AV1500 = new javax.swing.JLabel();
        LV1500 = new javax.swing.JLabel();
        PoliDeportivo = new javax.swing.JLabel();
        CentroIdiomas = new javax.swing.JLabel();
        AudioVisual = new javax.swing.JLabel();
        LV500 = new javax.swing.JLabel();
        PasilloEstudiantil = new javax.swing.JLabel();
        CISCO = new javax.swing.JLabel();
        AlbercaOlimpica = new javax.swing.JLabel();
        Kiawa = new javax.swing.JLabel();
        CAD = new javax.swing.JLabel();
        Resiedencias = new javax.swing.JLabel();
        LV1800 = new javax.swing.JLabel();
        AV800 = new javax.swing.JLabel();
        Biblioteca = new javax.swing.JLabel();
        AV600 = new javax.swing.JLabel();
        AV700 = new javax.swing.JLabel();
        LV300 = new javax.swing.JLabel();
        Alamos = new javax.swing.JLabel();
        LV1100 = new javax.swing.JLabel();
        CanchaTennis = new javax.swing.JLabel();
        LV1200 = new javax.swing.JLabel();
        RegistroEscolar = new javax.swing.JLabel();
        AV1600 = new javax.swing.JLabel();
        LV800 = new javax.swing.JLabel();
        LV700 = new javax.swing.JLabel();
        AV1100 = new javax.swing.JLabel();
        AV1200 = new javax.swing.JLabel();
        AV1300 = new javax.swing.JLabel();
        Enfermeria = new javax.swing.JLabel();
        Tutorias = new javax.swing.JLabel();
        Label_LogoITSON = new javax.swing.JLabel();
        AV1700 = new javax.swing.JLabel();
        Cultura = new javax.swing.JLabel();
        Movilidad = new javax.swing.JLabel();
        LV900 = new javax.swing.JLabel();
        AV900 = new javax.swing.JLabel();
        CasaClub = new javax.swing.JLabel();
        AulaMagna = new javax.swing.JLabel();
        Label_Mapa = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        Boton_PuntosDeInteres = new javax.swing.JButton();
        txtBusqueda = new javax.swing.JTextField();
        btnCerrar = new javax.swing.JButton();
        contenido = new javax.swing.JPanel();
        imagen = new javax.swing.JLabel();
        texto = new javax.swing.JLabel();
        NombreEdificio = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        lblUsuarioBienvenida = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mapa ITSON");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        AV1400.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AV1400.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AV1400MouseClicked(evt);
            }
        });

        AV1000.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AV1000.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AV1000MouseClicked(evt);
            }
        });

        AV1500.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AV1500.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AV1500MouseClicked(evt);
            }
        });

        LV1500.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LV1500.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LV1500MouseClicked(evt);
            }
        });

        PoliDeportivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PoliDeportivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PoliDeportivoMouseClicked(evt);
            }
        });

        CentroIdiomas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CentroIdiomas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CentroIdiomasMouseClicked(evt);
            }
        });

        AudioVisual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AudioVisual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AudioVisualMouseClicked(evt);
            }
        });

        LV500.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LV500.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LV500MouseClicked(evt);
            }
        });

        PasilloEstudiantil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PasilloEstudiantil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PasilloEstudiantilMouseClicked(evt);
            }
        });

        CISCO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CISCO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CISCOMouseClicked(evt);
            }
        });

        AlbercaOlimpica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AlbercaOlimpica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AlbercaOlimpicaMouseClicked(evt);
            }
        });

        Kiawa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Kiawa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KiawaMouseClicked(evt);
            }
        });

        CAD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CAD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CADMouseClicked(evt);
            }
        });

        Resiedencias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Resiedencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResiedenciasMouseClicked(evt);
            }
        });

        LV1800.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LV1800.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LV1800MouseClicked(evt);
            }
        });

        AV800.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AV800.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AV800MouseClicked(evt);
            }
        });

        Biblioteca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Biblioteca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BibliotecaMouseClicked(evt);
            }
        });

        AV600.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AV600.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AV600MouseClicked(evt);
            }
        });

        AV700.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AV700.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AV700MouseClicked(evt);
            }
        });

        LV300.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LV300.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LV300MouseClicked(evt);
            }
        });

        Alamos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Alamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AlamosMouseClicked(evt);
            }
        });

        LV1100.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LV1100.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LV1100MouseClicked(evt);
            }
        });

        CanchaTennis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CanchaTennis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CanchaTennisMouseClicked(evt);
            }
        });

        LV1200.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LV1200.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LV1200MouseClicked(evt);
            }
        });

        RegistroEscolar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegistroEscolar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistroEscolarMouseClicked(evt);
            }
        });

        AV1600.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AV1600.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AV1600MouseClicked(evt);
            }
        });

        LV800.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LV800.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LV800MouseClicked(evt);
            }
        });

        LV700.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LV700.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LV700MouseClicked(evt);
            }
        });

        AV1100.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AV1100.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AV1100MouseClicked(evt);
            }
        });

        AV1200.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AV1200.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AV1200MouseClicked(evt);
            }
        });

        AV1300.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AV1300.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AV1300MouseClicked(evt);
            }
        });

        Enfermeria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Enfermeria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EnfermeriaMouseClicked(evt);
            }
        });

        Tutorias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tutorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TutoriasMouseClicked(evt);
            }
        });

        Label_LogoITSON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo_ITSON (1)_1.png"))); // NOI18N

        AV1700.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AV1700.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AV1700MouseClicked(evt);
            }
        });

        Cultura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cultura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CulturaMouseClicked(evt);
            }
        });

        Movilidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Movilidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MovilidadMouseClicked(evt);
            }
        });

        LV900.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LV900.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LV900MouseClicked(evt);
            }
        });

        AV900.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AV900.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AV900MouseClicked(evt);
            }
        });

        CasaClub.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CasaClub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CasaClubMouseClicked(evt);
            }
        });

        AulaMagna.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AulaMagna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AulaMagnaMouseClicked(evt);
            }
        });

        Label_Mapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/croquis-nainari.png"))); // NOI18N

        jSeparator2.setForeground(new java.awt.Color(0, 102, 153));
        jSeparator2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(25, 111, 196));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Boton_PuntosDeInteres.setBackground(new java.awt.Color(231, 231, 231));
        Boton_PuntosDeInteres.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Boton_PuntosDeInteres.setForeground(new java.awt.Color(25, 111, 196));
        Boton_PuntosDeInteres.setText("Puntos interés");
        Boton_PuntosDeInteres.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Boton_PuntosDeInteres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_PuntosDeInteresActionPerformed(evt);
            }
        });
        jPanel2.add(Boton_PuntosDeInteres, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, -1, -1));

        txtBusqueda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBusqueda.setForeground(new java.awt.Color(51, 51, 51));
        txtBusqueda.setText("Búsqueda...");
        txtBusqueda.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaActionPerformed(evt);
            }
        });
        jPanel2.add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 190, 30));

        btnCerrar.setBackground(new java.awt.Color(231, 231, 231));
        btnCerrar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(25, 111, 196));
        btnCerrar.setText("Cerrar");
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 90, -1));

        contenido.setBackground(new java.awt.Color(255, 255, 255));
        contenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        contenido.add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 210, 130));

        texto.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        texto.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        texto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        texto.setInheritsPopupMenu(false);
        contenido.add(texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 210, 170));

        NombreEdificio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        contenido.add(NombreEdificio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 20));

        jPanel2.add(contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 230, 357));

        btnMenu.setBackground(new java.awt.Color(25, 111, 196));
        btnMenu.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu.png"))); // NOI18N
        btnMenu.setBorder(null);
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        lblUsuarioBienvenida.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Label_LogoITSON, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblUsuarioBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnMenu))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(AV1500, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170)
                .addComponent(AV600, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(AV1600, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(CAD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(Biblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(AulaMagna, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(325, 325, 325)
                .addComponent(AV1000, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(AlbercaOlimpica, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(CasaClub, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(CISCO, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(AV1400, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(RegistroEscolar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(AV900, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(LV700, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(AudioVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(LV1200, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(Alamos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(Enfermeria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(Cultura, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(AV1700, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(AV1200, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(Tutorias, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(370, 370, 370)
                .addComponent(AV800, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(410, 410, 410)
                .addComponent(Resiedencias, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(LV1100, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(370, 370, 370)
                .addComponent(AV700, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(LV300, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(CanchaTennis, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(Movilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(CentroIdiomas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(LV900, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(LV500, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(Kiawa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(PasilloEstudiantil, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(PoliDeportivo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(AV1100, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(Label_Mapa, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(AV1300, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(LV1800, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(LV800, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(LV1500, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(600, 600, 600)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_LogoITSON, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblUsuarioBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnMenu)))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(AV1500, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(AV600, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(AV1600, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addComponent(CAD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(Biblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(AulaMagna, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(AV1000, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(AlbercaOlimpica, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addComponent(CasaClub, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(CISCO, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(AV1400, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(RegistroEscolar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(AV900, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(LV700, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(AudioVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(LV1200, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(357, 357, 357)
                        .addComponent(Alamos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(Enfermeria, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(417, 417, 417)
                        .addComponent(Cultura, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(AV1700, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(AV1200, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(Tutorias, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(AV800, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(Resiedencias, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(LV1100, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(AV700, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(377, 377, 377)
                        .addComponent(LV300, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(CanchaTennis, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(387, 387, 387)
                        .addComponent(Movilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(377, 377, 377)
                        .addComponent(CentroIdiomas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(LV900, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(LV500, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(Kiawa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(357, 357, 357)
                        .addComponent(PasilloEstudiantil, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(PoliDeportivo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(AV1100, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(Label_Mapa, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(AV1300, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(LV1800, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(LV800, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(LV1500, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void bienvenidaSesion() {
        if (sesion != null) {
            lblUsuarioBienvenida.setText("Bienvenido " + sesion.getDatos().getNombre() + "!");
        }
    }
    
    public void mostrarPuntos(List<JLabel> puntos) {
    for (JLabel punto : puntos) {
        // Agrega el JLabel al jPanel1 con las coordenadas adecuadas
        jPanel1.add(punto);
    }
}
    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        if (sesion == null) {
            String[] botones = {"Sí", "No"};

            int opcion = JOptionPane.showOptionDialog(null, "Tiene que tener una sesión iniciada para acceder al menú. "
                    + "\n¿Desea iniciar sesión?",
                    "Acceder a menú", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,
                    null, botones, botones[0]);
            if (opcion == 0) {
                control.desplegarInicioSesion();
                dispose();
            } else {
                return;
            }
        } else {
            control.desplegarMenu();
            dispose();
        }
    }//GEN-LAST:event_btnMenuActionPerformed

    private void Boton_PuntosDeInteresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_PuntosDeInteresActionPerformed
        if (puntosVisibles) {
            this.mostrarPuntosDeInteres(Biblioteca, true);
            this.mostrarPuntosDeInteres(PasilloEstudiantil, true);
            this.mostrarPuntosDeInteres(Kiawa, true);
            this.mostrarPuntosDeInteres(CISCO, true);
            this.mostrarPuntosDeInteres(Alamos, true);
            this.mostrarPuntosDeInteres(RegistroEscolar, true);
            puntosVisibles = false;
        } else {
            this.mostrarPuntosDeInteres(Biblioteca, false);
            this.mostrarPuntosDeInteres(PasilloEstudiantil, false);
            this.mostrarPuntosDeInteres(Kiawa, false);
            this.mostrarPuntosDeInteres(CISCO, false);
            this.mostrarPuntosDeInteres(Alamos, false);
            this.mostrarPuntosDeInteres(RegistroEscolar, false);
            puntosVisibles = true;
        }
    }//GEN-LAST:event_Boton_PuntosDeInteresActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        String[] botones = {"Si", "No"};
        int variable = JOptionPane.showOptionDialog(null, "¿Desea cerrar la aplicacion?",
                "Pregunta", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,
                null, botones, botones[0]);
        if (variable == 0) {
            dispose();
        } else {
            return;
        }
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * Toma un array de bytes de la base de datos y la muestra como una imagen
     * en el lateral de la aplicacion
     *
     * @param imagenBytes el array de bytes sacado de la DB que representa una
     * imagen
     */
    public void mostrarImagen(byte[] imagenBytes) {
        ImageIcon icon = new ImageIcon(imagenBytes);
        imagen.setIcon(icon);
    }

    /**
     * Muestra en el panel lateral el nombre de la locacion, su descripcion y su
     * imagen, todo sacado desde la base de datos
     *
     * @param sesionLocacion
     */
    public void mostrarInformacion(LocacionPOJO sesionLocacion) {
        if (sesionLocacion != null) {
            NombreEdificio.setText("");
            texto.setText("");
            NombreEdificio.setText(sesionLocacion.getNombre());
            texto.setText("<html>" + sesionLocacion.getDescripcion() + "</html>");
            this.mostrarImagen(sesionLocacion.getImagen());
        }
    }

    /**
     * Metodo que se llama cuando un label es clickeado para cambiar su icon de
     * none a la flecha de localizacion
     *
     * @param label el label que vamos a modificar
     * @param bo si es true, se mostrar el icon, si es false, se desactivara
     */
    public void mostrarPunto(JLabel label, boolean bo) {
        if (ultimoLabelActivado != null) {
            ultimoLabelActivado.setIcon(null);
        }

        if (bo) {
            String imagePath = "/imagenes/5860579.png";
            String absolutePath = getClass().getResource(imagePath).getPath();
            ImageIcon icon = new ImageIcon(absolutePath);
            label.setIcon(icon);
            ultimoLabelActivado = label;
        } else {
            label.setIcon(null);
            ultimoLabelActivado = null;
        }
    }

    /**
     * Metodo para activar todos los puntos de interes a la vez, funciona igual
     * que mostrarPunto, pero ignorando la condicion de activar uno solo a la
     * vez
     *
     * @param label
     * @param bo
     */
    public void mostrarPuntosDeInteres(JLabel label, boolean bo) {
        if (bo) {
            String imagePath = "/imagenes/5860579.png";
            String absolutePath = getClass().getResource(imagePath).getPath();
            ImageIcon icon = new ImageIcon(absolutePath);
            label.setIcon(icon);
        } else {
            label.setIcon(null);
        }
    }
public void asignarEventos(List<JLabel> puntosInteres) {
    for (JLabel punto : puntos) {
            punto.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    // Aquí puedes definir lo que sucede cuando se hace clic en un punto
                    // Por ejemplo, mostrar información sobre la locación asociada al punto
                    String nombreLocacion = punto.getName();
                    LocacionPOJO locacion = vLocacion.verificarLocacion(nombreLocacion);
                    mostrarInformacion(locacion);
                    mostrarPunto(punto,true);
                }
            });
        }
    }

    private void CISCOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CISCOMouseClicked
        sesionLocacion = vLocacion.verificarLocacion("Cisco");
        this.mostrarInformacion(sesionLocacion);
        this.mostrarPunto(CISCO, true);
    }//GEN-LAST:event_CISCOMouseClicked

    private void KiawaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KiawaMouseClicked
        sesionLocacion = vLocacion.verificarLocacion("Kiawa");
        this.mostrarInformacion(sesionLocacion);
        this.mostrarPunto(Kiawa, true);
    }//GEN-LAST:event_KiawaMouseClicked

    private void AlamosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlamosMouseClicked
        sesionLocacion = vLocacion.verificarLocacion("Alamos");
        this.mostrarInformacion(sesionLocacion);
        this.mostrarPunto(Alamos, true);
    }//GEN-LAST:event_AlamosMouseClicked

    private void BibliotecaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BibliotecaMouseClicked
        sesionLocacion = vLocacion.verificarLocacion("Biblioteca");
        this.mostrarInformacion(sesionLocacion);
        this.mostrarPunto(Biblioteca, true);
    }//GEN-LAST:event_BibliotecaMouseClicked

    private void PasilloEstudiantilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasilloEstudiantilMouseClicked
        sesionLocacion = vLocacion.verificarLocacion("Pasillo estudiantil");
        this.mostrarInformacion(sesionLocacion);
        this.mostrarPunto(PasilloEstudiantil, true);
    }//GEN-LAST:event_PasilloEstudiantilMouseClicked

    private void RegistroEscolarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistroEscolarMouseClicked
        sesionLocacion = vLocacion.verificarLocacion("Registro escolar");
        this.mostrarInformacion(sesionLocacion);
        this.mostrarPunto(RegistroEscolar, true);
    }//GEN-LAST:event_RegistroEscolarMouseClicked

    private void LV1500MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LV1500MouseClicked
        sesionLocacion = vLocacion.verificarLocacion("LV1500");
        this.mostrarInformacion(sesionLocacion);
        this.mostrarPunto(LV1500, true);
    }//GEN-LAST:event_LV1500MouseClicked

    private void LV1200MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LV1200MouseClicked
        sesionLocacion = vLocacion.verificarLocacion("LV1200");
        this.mostrarInformacion(sesionLocacion);
        this.mostrarPunto(LV1200, true);
    }//GEN-LAST:event_LV1200MouseClicked

    private void PoliDeportivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PoliDeportivoMouseClicked
        this.mostrarPunto(PoliDeportivo, true);
        sesionLocacion = vLocacion.verificarLocacion("PoliDeportivo");
        this.mostrarInformacion(sesionLocacion);
    }//GEN-LAST:event_PoliDeportivoMouseClicked

    private void CanchaTennisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CanchaTennisMouseClicked
        this.mostrarPunto(CanchaTennis, true);
        sesionLocacion = vLocacion.verificarLocacion("CanchaTennis");
        this.mostrarInformacion(sesionLocacion);
    }//GEN-LAST:event_CanchaTennisMouseClicked

    private void CasaClubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CasaClubMouseClicked
        this.mostrarPunto(CasaClub, true);
        sesionLocacion = vLocacion.verificarLocacion("CasaClub");
        this.mostrarInformacion(sesionLocacion);
    }//GEN-LAST:event_CasaClubMouseClicked

    private void MovilidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovilidadMouseClicked
        this.mostrarPunto(Movilidad, true);
        sesionLocacion = vLocacion.verificarLocacion("Movilidad");
        this.mostrarInformacion(sesionLocacion);
    }//GEN-LAST:event_MovilidadMouseClicked

    private void CulturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CulturaMouseClicked
        this.mostrarPunto(Cultura, true);
        sesionLocacion = vLocacion.verificarLocacion("Cultural");
        this.mostrarInformacion(sesionLocacion);
    }//GEN-LAST:event_CulturaMouseClicked

    private void AV1700MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AV1700MouseClicked
        this.mostrarPunto(AV1700, true);
        sesionLocacion = vLocacion.verificarLocacion("AV1700");
        this.mostrarInformacion(sesionLocacion);
    }//GEN-LAST:event_AV1700MouseClicked

    private void TutoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TutoriasMouseClicked
        this.mostrarPunto(Tutorias, true);
        sesionLocacion = vLocacion.verificarLocacion("Tutorias");
        this.mostrarInformacion(sesionLocacion);
    }//GEN-LAST:event_TutoriasMouseClicked

    private void LV1100MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LV1100MouseClicked
        this.mostrarPunto(LV1100, true);
        sesionLocacion = vLocacion.verificarLocacion("LV1100");
        this.mostrarInformacion(sesionLocacion);
    }//GEN-LAST:event_LV1100MouseClicked

    private void AV1600MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AV1600MouseClicked
        this.mostrarPunto(AV1600, true);
        sesionLocacion = vLocacion.verificarLocacion("AV1600");
        this.mostrarInformacion(sesionLocacion);
    }//GEN-LAST:event_AV1600MouseClicked

    private void AV1500MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AV1500MouseClicked
        this.mostrarPunto(AV1500, true);
        sesionLocacion = vLocacion.verificarLocacion("AV1500");
        this.mostrarInformacion(sesionLocacion);
    }//GEN-LAST:event_AV1500MouseClicked

    private void AV1400MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AV1400MouseClicked
        this.mostrarPunto(AV1400, true);
        sesionLocacion = vLocacion.verificarLocacion("AV1400");
        this.mostrarInformacion(sesionLocacion);
    }//GEN-LAST:event_AV1400MouseClicked

    private void CADMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CADMouseClicked
        this.mostrarPunto(CAD, true);
        sesionLocacion = vLocacion.verificarLocacion("CAD");
        this.mostrarInformacion(sesionLocacion);
    }//GEN-LAST:event_CADMouseClicked

    private void CentroIdiomasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CentroIdiomasMouseClicked
        this.mostrarPunto(CentroIdiomas, true);
        sesionLocacion = vLocacion.verificarLocacion("Idiomas");
        this.mostrarInformacion(sesionLocacion);
    }//GEN-LAST:event_CentroIdiomasMouseClicked

    private void AudioVisualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AudioVisualMouseClicked
        this.mostrarPunto(AudioVisual, true);
        sesionLocacion = vLocacion.verificarLocacion("AudioVisual");
        this.mostrarInformacion(sesionLocacion);
    }//GEN-LAST:event_AudioVisualMouseClicked

    private void LV700MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LV700MouseClicked
        this.mostrarPunto(LV700, true);
        sesionLocacion = vLocacion.verificarLocacion("LV700");
        this.mostrarInformacion(sesionLocacion);
    }//GEN-LAST:event_LV700MouseClicked

    private void LV800MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LV800MouseClicked
        this.mostrarPunto(LV800, true);
        sesionLocacion = vLocacion.verificarLocacion("LV800");
        this.mostrarInformacion(sesionLocacion);
    }//GEN-LAST:event_LV800MouseClicked

    private void AV1300MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AV1300MouseClicked
        this.mostrarPunto(AV1300, true);
        sesionLocacion = vLocacion.verificarLocacion("AV1300");
        this.mostrarInformacion(sesionLocacion);
    }//GEN-LAST:event_AV1300MouseClicked

    private void AV1200MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AV1200MouseClicked
        this.mostrarPunto(AV1200, true);
        sesionLocacion = vLocacion.verificarLocacion("AV1200");
        this.mostrarInformacion(sesionLocacion);
    }//GEN-LAST:event_AV1200MouseClicked

    private void AV1100MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AV1100MouseClicked
        this.mostrarPunto(AV1100, true);
        sesionLocacion = vLocacion.verificarLocacion("AV1100");
        this.mostrarInformacion(sesionLocacion);
    }//GEN-LAST:event_AV1100MouseClicked

    private void LV500MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LV500MouseClicked
        this.mostrarPunto(LV500, true);
        sesionLocacion = vLocacion.verificarLocacion("LV500");
        this.mostrarInformacion(sesionLocacion);
    }//GEN-LAST:event_LV500MouseClicked

    private void EnfermeriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnfermeriaMouseClicked
        this.mostrarPunto(Enfermeria, true);
        sesionLocacion = vLocacion.verificarLocacion("Enfermeria");
        this.mostrarInformacion(sesionLocacion);
    }//GEN-LAST:event_EnfermeriaMouseClicked

    private void AulaMagnaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AulaMagnaMouseClicked
        this.mostrarPunto(AulaMagna, true);
        sesionLocacion = vLocacion.verificarLocacion("AulaMagna");
        this.mostrarInformacion(sesionLocacion);
    }//GEN-LAST:event_AulaMagnaMouseClicked

    private void LV300MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LV300MouseClicked
        this.mostrarPunto(LV300, true);
        sesionLocacion = vLocacion.verificarLocacion("LV300");
        this.mostrarInformacion(sesionLocacion);
    }//GEN-LAST:event_LV300MouseClicked

    private void AV1000MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AV1000MouseClicked
        this.mostrarPunto(AV1000, true);
        sesionLocacion = vLocacion.verificarLocacion("AV1000");
        this.mostrarInformacion(sesionLocacion);
    }//GEN-LAST:event_AV1000MouseClicked

    private void ResiedenciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResiedenciasMouseClicked
        this.mostrarPunto(Resiedencias, true);
        sesionLocacion = vLocacion.verificarLocacion("Residencias");
        this.mostrarInformacion(sesionLocacion);
    }//GEN-LAST:event_ResiedenciasMouseClicked

    private void AV800MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AV800MouseClicked
        this.mostrarPunto(AV800, true);
        sesionLocacion = vLocacion.verificarLocacion("AV800");
        this.mostrarInformacion(sesionLocacion);
    }//GEN-LAST:event_AV800MouseClicked

    private void AV700MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AV700MouseClicked
        this.mostrarPunto(AV700, true);
        sesionLocacion = vLocacion.verificarLocacion("AV700");
        this.mostrarInformacion(sesionLocacion);
    }//GEN-LAST:event_AV700MouseClicked

    private void AV600MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AV600MouseClicked
        this.mostrarPunto(AV600, true);
        sesionLocacion = vLocacion.verificarLocacion("AV600");
        this.mostrarInformacion(sesionLocacion);
    }//GEN-LAST:event_AV600MouseClicked

    private void AlbercaOlimpicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlbercaOlimpicaMouseClicked
        this.mostrarPunto(AlbercaOlimpica, true);
        sesionLocacion = vLocacion.verificarLocacion("AlbercaOlimpica");
        this.mostrarInformacion(sesionLocacion);
    }//GEN-LAST:event_AlbercaOlimpicaMouseClicked

    private void LV1800MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LV1800MouseClicked
        this.mostrarPunto(LV1800, true);
        sesionLocacion = vLocacion.verificarLocacion("LV1800");
        this.mostrarInformacion(sesionLocacion);
    }//GEN-LAST:event_LV1800MouseClicked

    private void LV900MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LV900MouseClicked
        this.mostrarPunto(LV900, true);
        sesionLocacion = vLocacion.verificarLocacion("LV900");
        this.mostrarInformacion(sesionLocacion);
    }//GEN-LAST:event_LV900MouseClicked

    private void AV900MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AV900MouseClicked
        this.mostrarPunto(AV900, true);
        sesionLocacion = vLocacion.verificarLocacion("AV900");
        this.mostrarInformacion(sesionLocacion);
    }//GEN-LAST:event_AV900MouseClicked

    private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AV1000;
    private javax.swing.JLabel AV1100;
    private javax.swing.JLabel AV1200;
    private javax.swing.JLabel AV1300;
    private javax.swing.JLabel AV1400;
    private javax.swing.JLabel AV1500;
    private javax.swing.JLabel AV1600;
    private javax.swing.JLabel AV1700;
    private javax.swing.JLabel AV600;
    private javax.swing.JLabel AV700;
    private javax.swing.JLabel AV800;
    private javax.swing.JLabel AV900;
    private javax.swing.JLabel Alamos;
    private javax.swing.JLabel AlbercaOlimpica;
    private javax.swing.JLabel AudioVisual;
    private javax.swing.JLabel AulaMagna;
    private javax.swing.JLabel Biblioteca;
    private javax.swing.JButton Boton_PuntosDeInteres;
    private javax.swing.JLabel CAD;
    private javax.swing.JLabel CISCO;
    private javax.swing.JLabel CanchaTennis;
    private javax.swing.JLabel CasaClub;
    private javax.swing.JLabel CentroIdiomas;
    private javax.swing.JLabel Cultura;
    private javax.swing.JLabel Enfermeria;
    private javax.swing.JLabel Kiawa;
    private javax.swing.JLabel LV1100;
    private javax.swing.JLabel LV1200;
    private javax.swing.JLabel LV1500;
    private javax.swing.JLabel LV1800;
    private javax.swing.JLabel LV300;
    private javax.swing.JLabel LV500;
    private javax.swing.JLabel LV700;
    private javax.swing.JLabel LV800;
    private javax.swing.JLabel LV900;
    private javax.swing.JLabel Label_LogoITSON;
    private javax.swing.JLabel Label_Mapa;
    private javax.swing.JLabel Movilidad;
    private javax.swing.JLabel NombreEdificio;
    private javax.swing.JLabel PasilloEstudiantil;
    private javax.swing.JLabel PoliDeportivo;
    private javax.swing.JLabel RegistroEscolar;
    private javax.swing.JLabel Resiedencias;
    private javax.swing.JLabel Tutorias;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JPanel contenido;
    private javax.swing.JLabel imagen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblUsuarioBienvenida;
    private javax.swing.JLabel texto;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
