package Vistas;

import Controladora.ControlPresentacion;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author RAUL EDUARDO GOMEZ
 */
public class frmMapa extends javax.swing.JFrame {

    ControlPresentacion control = new ControlPresentacion();

    /**
     * Creates new form MapaInteractivo
     *
     * @param parent
     * @param modal
     */
    public frmMapa(java.awt.Frame parent, boolean modal) {
        initComponents();
    }

    public frmMapa() {
        initComponents();

        txtBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBusquedaMouseClicked(evt);
            }

            private void txtBusquedaMouseClicked(MouseEvent evt) {
                if (txtBusqueda.getText().equals("Búsqueda...")) {
                    txtBusqueda.setText("");
                }
            }
        });
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ButtonRegreso = new javax.swing.JButton();
        AV1400 = new javax.swing.JLabel();
        AV1000 = new javax.swing.JLabel();
        AV1500 = new javax.swing.JLabel();
        LV1500 = new javax.swing.JLabel();
        PoliDeportivo = new javax.swing.JLabel();
        CentroIdiomas = new javax.swing.JLabel();
        AudioVisual = new javax.swing.JLabel();
        LV500 = new javax.swing.JLabel();
        PasilloEstudiantil = new javax.swing.JLabel();
        CISCO = new javax.swing.JLabel();
        AlbercaOlimpica = new javax.swing.JLabel();
        Kiawa = new javax.swing.JLabel();
        CAD = new javax.swing.JLabel();
        Resiedencias = new javax.swing.JLabel();
        LV1800 = new javax.swing.JLabel();
        AV800 = new javax.swing.JLabel();
        Biblioteca = new javax.swing.JLabel();
        AV600 = new javax.swing.JLabel();
        AV700 = new javax.swing.JLabel();
        LV300 = new javax.swing.JLabel();
        Alamos = new javax.swing.JLabel();
        LV1100 = new javax.swing.JLabel();
        CanchaTennis = new javax.swing.JLabel();
        Civil = new javax.swing.JLabel();
        RegistroEscolar = new javax.swing.JLabel();
        AV1600 = new javax.swing.JLabel();
        LV800 = new javax.swing.JLabel();
        LV700 = new javax.swing.JLabel();
        AV1100 = new javax.swing.JLabel();
        AV1200 = new javax.swing.JLabel();
        AV1300 = new javax.swing.JLabel();
        Enfermeria = new javax.swing.JLabel();
        Tutorias = new javax.swing.JLabel();
        Label_LogoITSON = new javax.swing.JLabel();
        AV1700 = new javax.swing.JLabel();
        Cultura = new javax.swing.JLabel();
        Movilidad = new javax.swing.JLabel();
        CasaClub = new javax.swing.JLabel();
        AulaMagna = new javax.swing.JLabel();
        Label_Mapa = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        txtBusqueda = new javax.swing.JTextField();
        Boton_PuntosDeInteres = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mapa ITSON");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonRegreso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButtonRegreso.setForeground(new java.awt.Color(255, 255, 255));
        ButtonRegreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-back.png"))); // NOI18N
        ButtonRegreso.setBorder(null);
        ButtonRegreso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonRegreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRegresoActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonRegreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 50, 40));

        AV1400.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5860579.png"))); // NOI18N
        jPanel1.add(AV1400, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, -1));
        AV1400.setVisible(false);

        AV1000.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5860579.png"))); // NOI18N
        jPanel1.add(AV1000, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, -1, -1));
        AV1000.setVisible(false);

        AV1500.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5860579.png"))); // NOI18N
        jPanel1.add(AV1500, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, -1, -1));
        AV1500.setVisible(false);

        LV1500.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5860579.png"))); // NOI18N
        jPanel1.add(LV1500, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));
        LV1500.setVisible(false);

        PoliDeportivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5860579.png"))); // NOI18N
        jPanel1.add(PoliDeportivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));
        PoliDeportivo.setVisible(false);

        CentroIdiomas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5860579.png"))); // NOI18N
        jPanel1.add(CentroIdiomas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, -1, -1));
        CentroIdiomas.setVisible(false);

        AudioVisual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5860579.png"))); // NOI18N
        jPanel1.add(AudioVisual, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, -1, -1));
        AudioVisual.setVisible(false);

        LV500.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5860579.png"))); // NOI18N
        jPanel1.add(LV500, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, -1, -1));
        LV500.setVisible(false);

        PasilloEstudiantil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5860579.png"))); // NOI18N
        PasilloEstudiantil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PasilloEstudiantilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PasilloEstudiantilMouseExited(evt);
            }
        });
        jPanel1.add(PasilloEstudiantil, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, -1, -1));
        PasilloEstudiantil.setVisible(false);

        CISCO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5860579.png"))); // NOI18N
        CISCO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CISCOMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CISCOMouseExited(evt);
            }
        });
        jPanel1.add(CISCO, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, -1, -1));
        CISCO.setVisible(false);

        AlbercaOlimpica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5860579.png"))); // NOI18N
        jPanel1.add(AlbercaOlimpica, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));
        AlbercaOlimpica.setVisible(false);

        Kiawa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5860579.png"))); // NOI18N
        Kiawa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                KiawaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                KiawaMouseExited(evt);
            }
        });
        jPanel1.add(Kiawa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, -1, -1));
        Kiawa.setVisible(false);

        CAD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5860579.png"))); // NOI18N
        jPanel1.add(CAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, -1, -1));
        CAD.setVisible(false);

        Resiedencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5860579.png"))); // NOI18N
        jPanel1.add(Resiedencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, -1, -1));
        Resiedencias.setVisible(false);

        LV1800.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5860579.png"))); // NOI18N
        jPanel1.add(LV1800, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));
        LV1800.setVisible(false);

        AV800.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5860579.png"))); // NOI18N
        jPanel1.add(AV800, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, -1, -1));
        AV800.setVisible(false);

        Biblioteca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5860579.png"))); // NOI18N
        Biblioteca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BibliotecaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BibliotecaMouseExited(evt);
            }
        });
        jPanel1.add(Biblioteca, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, -1, -1));
        Biblioteca.setVisible(false);

        AV600.setVisible(false);
        AV600.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5860579.png"))); // NOI18N
        jPanel1.add(AV600, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, -1, -1));

        AV700.setVisible(false);
        AV700.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5860579.png"))); // NOI18N
        jPanel1.add(AV700, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, -1, -1));

        LV300.setVisible(false);
        LV300.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5860579.png"))); // NOI18N
        jPanel1.add(LV300, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, -1, -1));

        Alamos.setVisible(false);
        Alamos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5860579.png"))); // NOI18N
        Alamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AlamosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AlamosMouseExited(evt);
            }
        });
        jPanel1.add(Alamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, -1, -1));

        LV1100.setVisible(false);
        LV1100.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5860579.png"))); // NOI18N
        jPanel1.add(LV1100, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, -1, -1));

        CanchaTennis.setVisible(false);
        CanchaTennis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5860579.png"))); // NOI18N
        jPanel1.add(CanchaTennis, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, -1, -1));

        Civil.setVisible(false);
        Civil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5860579.png"))); // NOI18N
        jPanel1.add(Civil, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, -1));

        RegistroEscolar.setVisible(false);
        RegistroEscolar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5860579.png"))); // NOI18N
        RegistroEscolar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegistroEscolarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegistroEscolarMouseExited(evt);
            }
        });
        jPanel1.add(RegistroEscolar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, -1, -1));

        AV1600.setVisible(false);
        AV1600.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5860579.png"))); // NOI18N
        jPanel1.add(AV1600, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, -1));

        LV800.setVisible(false);
        LV800.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5860579.png"))); // NOI18N
        jPanel1.add(LV800, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, -1, -1));

        LV700.setVisible(false);
        LV700.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5860579.png"))); // NOI18N
        jPanel1.add(LV700, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, -1, -1));

        AV1100.setVisible(false);
        AV1100.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5860579.png"))); // NOI18N
        jPanel1.add(AV1100, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, -1, -1));

        AV1200.setVisible(false);
        AV1200.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5860579.png"))); // NOI18N
        jPanel1.add(AV1200, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, -1));

        AV1300.setVisible(false);
        AV1300.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5860579.png"))); // NOI18N
        jPanel1.add(AV1300, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, -1, -1));

        Enfermeria.setVisible(false);
        Enfermeria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5860579.png"))); // NOI18N
        jPanel1.add(Enfermeria, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, -1, -1));

        Tutorias.setVisible(false);
        Tutorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5860579.png"))); // NOI18N
        jPanel1.add(Tutorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, -1, -1));

        Label_LogoITSON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo_ITSON (1)_1.png"))); // NOI18N
        jPanel1.add(Label_LogoITSON, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 250, 90));

        AV1700.setVisible(false);
        AV1700.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5860579.png"))); // NOI18N
        jPanel1.add(AV1700, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, -1, -1));

        Cultura.setVisible(false);
        Cultura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5860579.png"))); // NOI18N
        jPanel1.add(Cultura, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, -1, -1));

        Movilidad.setVisible(false);
        Movilidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5860579.png"))); // NOI18N
        jPanel1.add(Movilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, -1, -1));

        CasaClub.setVisible(false);
        CasaClub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5860579.png"))); // NOI18N
        jPanel1.add(CasaClub, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, -1, -1));

        AulaMagna.setVisible(false);
        AulaMagna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5860579.png"))); // NOI18N
        jPanel1.add(AulaMagna, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, -1, -1));

        Label_Mapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/croquis-nainari.jpg"))); // NOI18N
        jPanel1.add(Label_Mapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 600, 450));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 850, 12));

        jPanel2.setBackground(new java.awt.Color(25, 111, 196));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBusqueda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBusqueda.setText("Búsqueda...");
        txtBusqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaActionPerformed(evt);
            }
        });
        jPanel2.add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 102, 238, 30));

        Boton_PuntosDeInteres.setBackground(new java.awt.Color(231, 231, 231));
        Boton_PuntosDeInteres.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Boton_PuntosDeInteres.setForeground(new java.awt.Color(25, 111, 196));
        Boton_PuntosDeInteres.setText("Puntos interés");
        Boton_PuntosDeInteres.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton_PuntosDeInteres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_PuntosDeInteresActionPerformed(evt);
            }
        });
        jPanel2.add(Boton_PuntosDeInteres, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 509, -1, -1));

        btnCerrar.setBackground(new java.awt.Color(231, 231, 231));
        btnCerrar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(25, 111, 196));
        btnCerrar.setText("Cerrar");
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 509, 77, -1));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 230, 30));

        lblDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        lblDescripcion.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(lblDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 230, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 250, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed
        
    }//GEN-LAST:event_txtBusquedaActionPerformed


    private boolean puntosVisibles = false;

    private void Boton_PuntosDeInteresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_PuntosDeInteresActionPerformed

        if (puntosVisibles) {
            Biblioteca.setVisible(false);
            PasilloEstudiantil.setVisible(false);
            Kiawa.setVisible(false);
            CISCO.setVisible(false);
            Alamos.setVisible(false);
            RegistroEscolar.setVisible(false);
            puntosVisibles = false;
        } else {
            Biblioteca.setVisible(true);
            PasilloEstudiantil.setVisible(true);
            Kiawa.setVisible(true);
            CISCO.setVisible(true);
            Alamos.setVisible(true);
            RegistroEscolar.setVisible(true);
            puntosVisibles = true;
        }

    }//GEN-LAST:event_Boton_PuntosDeInteresActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        String[] botones = {"Si", "No"};

        int variable = JOptionPane.showOptionDialog(null, "¿Desea cerrar la aplicacion?", 
                "Confirmación", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, 
                null/*icono*/, botones, botones[0]);

        if (variable == 0) {
            dispose();
        } else {
            return;
        }
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void ButtonRegresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRegresoActionPerformed
        control.deplegarMenu();
        dispose();
    }//GEN-LAST:event_ButtonRegresoActionPerformed

    private void CISCOMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CISCOMouseEntered
        lblNombre.setText("CISCO");
        lblDescripcion.setText("<html>Cuenta con 478 computadoras, distribuidos en: "
            + "Laboratorios de cómputo, aulas interactivas, "
            + "1 laboratorio y 1 aula de diseño gráfico.</html>");
    }//GEN-LAST:event_CISCOMouseEntered

    private void CISCOMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CISCOMouseExited
        lblNombre.setText("");
        lblDescripcion.setText("");
    }//GEN-LAST:event_CISCOMouseExited

    private void RegistroEscolarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistroEscolarMouseEntered
        lblNombre.setText("Registro Escolar");
        lblDescripcion.setText("<html>Área de autoservicio de alumnos y maestros, análisis de procesos, "
                + "Cédula en línea, Titulación Web.</html>");
    }//GEN-LAST:event_RegistroEscolarMouseEntered

    private void RegistroEscolarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistroEscolarMouseExited
        lblNombre.setText("");
        lblDescripcion.setText("");
    }//GEN-LAST:event_RegistroEscolarMouseExited

    private void BibliotecaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BibliotecaMouseEntered
        lblNombre.setText("Biblioteca");
        lblDescripcion.setText("<html>Servicios presenciales: Consulta en Sala, Préstamo de Acervo a"
                + " Domicilio, Cubículos de Estudio Grupal, Capacitación, entre otros.</html>");
    }//GEN-LAST:event_BibliotecaMouseEntered

    private void BibliotecaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BibliotecaMouseExited
        lblNombre.setText("");
        lblDescripcion.setText("");
    }//GEN-LAST:event_BibliotecaMouseExited

    private void PasilloEstudiantilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasilloEstudiantilMouseEntered
        lblNombre.setText("Pasillo Estudiantil");
        lblDescripcion.setText("<html>Centro de Servicios Estudiantiles, "
                + "\nComedor Estudiantil con horario de 8:00 a.m a  4:00 p.m.</html>");
    }//GEN-LAST:event_PasilloEstudiantilMouseEntered

    private void PasilloEstudiantilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasilloEstudiantilMouseExited
        lblNombre.setText("");
        lblDescripcion.setText("");
    }//GEN-LAST:event_PasilloEstudiantilMouseExited

    private void KiawaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KiawaMouseEntered
        lblNombre.setText("Cafetería Kiawa");
        lblDescripcion.setText("<html>Horario de 8:00 a.m a  4:00 p.m.​</html>");
    }//GEN-LAST:event_KiawaMouseEntered

    private void KiawaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KiawaMouseExited
        lblNombre.setText("");
        lblDescripcion.setText("");
    }//GEN-LAST:event_KiawaMouseExited

    private void AlamosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlamosMouseEntered
        lblNombre.setText("Cafetería Potros");
        lblDescripcion.setText("<html>Horario de 8:00 a.m a  7:00 p.m.</html>");
    }//GEN-LAST:event_AlamosMouseEntered

    private void AlamosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlamosMouseExited
        lblNombre.setText("");
        lblDescripcion.setText("");
    }//GEN-LAST:event_AlamosMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmMapa dialog = new frmMapa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AV1000;
    private javax.swing.JLabel AV1100;
    private javax.swing.JLabel AV1200;
    private javax.swing.JLabel AV1300;
    private javax.swing.JLabel AV1400;
    private javax.swing.JLabel AV1500;
    private javax.swing.JLabel AV1600;
    private javax.swing.JLabel AV1700;
    private javax.swing.JLabel AV600;
    private javax.swing.JLabel AV700;
    private javax.swing.JLabel AV800;
    private javax.swing.JLabel Alamos;
    private javax.swing.JLabel AlbercaOlimpica;
    private javax.swing.JLabel AudioVisual;
    private javax.swing.JLabel AulaMagna;
    private javax.swing.JLabel Biblioteca;
    private javax.swing.JButton Boton_PuntosDeInteres;
    private javax.swing.JButton ButtonRegreso;
    private javax.swing.JLabel CAD;
    private javax.swing.JLabel CISCO;
    private javax.swing.JLabel CanchaTennis;
    private javax.swing.JLabel CasaClub;
    private javax.swing.JLabel CentroIdiomas;
    private javax.swing.JLabel Civil;
    private javax.swing.JLabel Cultura;
    private javax.swing.JLabel Enfermeria;
    private javax.swing.JLabel Kiawa;
    private javax.swing.JLabel LV1100;
    private javax.swing.JLabel LV1500;
    private javax.swing.JLabel LV1800;
    private javax.swing.JLabel LV300;
    private javax.swing.JLabel LV500;
    private javax.swing.JLabel LV700;
    private javax.swing.JLabel LV800;
    private javax.swing.JLabel Label_LogoITSON;
    private javax.swing.JLabel Label_Mapa;
    private javax.swing.JLabel Movilidad;
    private javax.swing.JLabel PasilloEstudiantil;
    private javax.swing.JLabel PoliDeportivo;
    private javax.swing.JLabel RegistroEscolar;
    private javax.swing.JLabel Resiedencias;
    private javax.swing.JLabel Tutorias;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
